name = "readbusinessworker"
main = "src/index.ts"
compatibility_date = "2022-11-13"

[vars]
MONGO_DB_APP_ID = "application-0-jgbve"
MONGO_DB_API_KEY = "HSUskedJXn9NZmrOyXbiHbdJTpy2YPKVHLNagQdcLL1uB3KlUI4qraiwJ4VcuEBc"
[dev]
port= 5173